#!/usr/bin/env bash
# =============================================================================
# 00_setup.sh — Environment setup for CheFF fine-tuning
#
# Usage:
#   bash 00_setup.sh
#
# After running, activate the environment and run:
#   cd cheff_peft && python -m finetune_cheff.train
# =============================================================================
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "============================================="
echo " Applied DL — Environment Setup"
echo " Project root : $PROJECT_ROOT"
echo "============================================="

# ---------------------------------------------------------------------------
# 1. Create / activate virtualenv
# ---------------------------------------------------------------------------
VENV_DIR="$PROJECT_ROOT/adl_env"
if [ ! -d "$VENV_DIR" ]; then
    echo "[1/4] Creating virtualenv at $VENV_DIR ..."
    python3 -m venv "$VENV_DIR"
else
    echo "[1/4] Virtualenv already exists — skipping creation."
fi

# shellcheck source=/dev/null
source "$VENV_DIR/bin/activate"
pip install --upgrade pip --quiet

# ---------------------------------------------------------------------------
# 2. Install all dependencies (torch cu121 + base requirements)
# ---------------------------------------------------------------------------
echo "[2/4] Installing dependencies from requirements/gpu.txt ..."
pip install -r "$PROJECT_ROOT/requirements/gpu.txt" --quiet

# Ensure numpy stays pinned (some packages try to upgrade it)
pip install "numpy==1.26.4" --quiet

# ---------------------------------------------------------------------------
# 3. Fix taming-transformers (pip install doesn't copy the module correctly)
# ---------------------------------------------------------------------------
echo "[3/4] Installing taming-transformers ..."
SITE_PACKAGES="$(python -c "import site; print(site.getsitepackages()[0])")"

if [ ! -d "$SITE_PACKAGES/taming" ]; then
    TMP_TAMING=$(mktemp -d)
    git clone --depth 1 https://github.com/CompVis/taming-transformers.git "$TMP_TAMING" -q
    cp -r "$TMP_TAMING/taming" "$SITE_PACKAGES/taming"
    rm -rf "$TMP_TAMING"
    echo "  → taming installed"
else
    echo "  → taming already present — skipping."
fi

# ---------------------------------------------------------------------------
# 4. Create .env if it does not exist
# ---------------------------------------------------------------------------
echo "[4/4] Checking .env ..."
ENV_FILE="$PROJECT_ROOT/.env"

if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << EOF
# Auto-generated by 00_setup.sh — edit as needed
MACHEX_OUTPUT_DIR=$PROJECT_ROOT/machex_dataset/vindr-pcxr
ACCELERATOR=gpu
EOF
    echo "  → .env created"
else
    echo "  → .env already exists — skipping."
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "============================================="
echo " Setup complete!"
echo ""
echo " Activate: source $VENV_DIR/bin/activate"
echo ""
echo " Download checkpoints (if not already done):"
echo "   mkdir -p $PROJECT_ROOT/cheff_peft/checkpoints"
echo "   wget -O $PROJECT_ROOT/cheff_peft/checkpoints/cheff_diff_t2i.pt \\"
echo "     'https://syncandshare.lrz.de/dl/fi4R87B3cEWgSx4Wivyizb/cheff_diff_t2i.pt'"
echo ""
echo " Run training:"
echo "   cd $PROJECT_ROOT/cheff_peft && python -m finetune_cheff.train"
echo "============================================="
