#!/usr/bin/env bash
# =============================================================================
# 00_setup.sh — Environment setup for CheFF fine-tuning
#
# Supports:
#   - LMU MCML cluster  (x86_64, CUDA 12.1, SLURM)
#   - Lambda cloud GPU  (aarch64, CUDA bundled in plain wheels)
#   - Local macOS CPU   (no CUDA)
#
# Usage:
#   bash 00_setup.sh
#
# The script will auto-detect the platform and install the right wheels.
# After running, activate the environment and run:
#   cd cheff_peft && python -m finetune_cheff.train
# =============================================================================
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ARCH="$(uname -m)"
OS="$(uname -s)"

echo "============================================="
echo " Applied DL — Environment Setup"
echo " Project root : $PROJECT_ROOT"
echo " Architecture : $ARCH"
echo " OS           : $OS"
echo "============================================="

# ---------------------------------------------------------------------------
# 1. Create / activate virtualenv
# ---------------------------------------------------------------------------
VENV_DIR="$PROJECT_ROOT/adl_env"
if [ ! -d "$VENV_DIR" ]; then
    echo "[1/5] Creating virtualenv at $VENV_DIR ..."
    python3 -m venv "$VENV_DIR"
else
    echo "[1/5] Virtualenv already exists at $VENV_DIR — skipping creation."
fi

# shellcheck source=/dev/null
source "$VENV_DIR/bin/activate"
pip install --upgrade pip --quiet

# ---------------------------------------------------------------------------
# 2. Install PyTorch (platform-specific)
# ---------------------------------------------------------------------------
echo "[2/5] Installing PyTorch ..."

if [ "$OS" = "Darwin" ]; then
    # macOS — CPU only
    echo "  → macOS detected: installing CPU-only torch"
    pip install torch==2.1.2 torchvision==0.16.2 --quiet

elif [ "$ARCH" = "aarch64" ]; then
    # ARM Linux (Lambda, etc.) — plain wheels bundle CUDA
    echo "  → aarch64 detected: installing plain torch (CUDA bundled)"
    pip install torch==2.1.2 torchvision==0.16.2 --quiet

elif [ "$ARCH" = "x86_64" ]; then
    # x86 Linux — use CUDA 12.1 wheels (LMU MCML cluster)
    echo "  → x86_64 detected: installing torch with CUDA 12.1"
    pip install torch==2.1.2+cu121 torchvision==0.16.2+cu121 \
        --extra-index-url https://download.pytorch.org/whl/cu121 --quiet

else
    echo "  WARNING: Unknown architecture '$ARCH' — installing plain torch"
    pip install torch==2.1.2 torchvision==0.16.2 --quiet
fi

# ---------------------------------------------------------------------------
# 3. Install base requirements
# ---------------------------------------------------------------------------
echo "[3/5] Installing base requirements ..."
pip install -r "$PROJECT_ROOT/requirements/base.txt" --quiet

# Pin numpy before anything re-upgrades it
pip install "numpy==1.26.4" --quiet

# ---------------------------------------------------------------------------
# 4. Fix taming-transformers (pip install is broken — copy manually)
# ---------------------------------------------------------------------------
echo "[4/5] Installing taming-transformers ..."
SITE_PACKAGES="$(python -c "import site; print(site.getsitepackages()[0])")"

if [ ! -d "$SITE_PACKAGES/taming" ]; then
    TMP_TAMING=$(mktemp -d)
    git clone --depth 1 https://github.com/CompVis/taming-transformers.git "$TMP_TAMING" -q
    cp -r "$TMP_TAMING/taming" "$SITE_PACKAGES/taming"
    rm -rf "$TMP_TAMING"
    echo "  → taming installed to $SITE_PACKAGES/taming"
else
    echo "  → taming already present — skipping."
fi

# ---------------------------------------------------------------------------
# 5. Create .env if it does not exist
# ---------------------------------------------------------------------------
echo "[5/5] Checking .env ..."
ENV_FILE="$PROJECT_ROOT/.env"

if [ ! -f "$ENV_FILE" ]; then
    # Auto-detect data path
    if [ "$OS" = "Darwin" ]; then
        ACCELERATOR="cpu"
    else
        ACCELERATOR="gpu"
    fi

    MACHEX_DIR="$PROJECT_ROOT/machex_dataset/vindr-pcxr"

    cat > "$ENV_FILE" << EOF
# Auto-generated by 00_setup.sh — edit as needed
MACHEX_OUTPUT_DIR=$MACHEX_DIR
ACCELERATOR=$ACCELERATOR
EOF
    echo "  → .env created (ACCELERATOR=$ACCELERATOR, MACHEX_OUTPUT_DIR=$MACHEX_DIR)"
else
    echo "  → .env already exists — skipping."
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "============================================="
echo " Setup complete!"
echo ""
echo " Next steps:"
echo "   source $VENV_DIR/bin/activate"
echo ""
echo " Download checkpoints (if not already done):"
echo "   mkdir -p $PROJECT_ROOT/cheff_peft/checkpoints"
echo "   wget -O $PROJECT_ROOT/cheff_peft/checkpoints/cheff_diff_t2i.pt \\"
echo "     'https://syncandshare.lrz.de/dl/fi4R87B3cEWgSx4Wivyizb/cheff_diff_t2i.pt'"
echo "   wget -O $PROJECT_ROOT/cheff_peft/checkpoints/cheff_autoencoder.pt \\"
echo "     '<AE_URL>'"
echo ""
echo " Then run training:"
echo "   cd $PROJECT_ROOT/cheff_peft && python -m finetune_cheff.train"
echo "============================================="
