MACHEX_PATH: machex_dataset
NUM_WORKERS: 8
FRONTAL_ONLY: true

CHEXRAY14_ROOT: null
CHEXPERT_ROOT: null
PADCHEST_ROOT: null
MIMIC_ROOT: null
VINDRCXR_ROOT: ../data/physionet.org/files/vindr-pcxr/1.0.0
BRAX_ROOT: null
RSNA_ROOT: null
OPENI_ROOT: null
SIIM_ROOT: null
OBJECTCXR_ROOT: null
